services:
  backstage-backend:
    build:
      context: backstage
      dockerfile: Dockerfile
    command:
      - yarn
      - start-backend
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
    ports:
      - 7007:7007
    volumes:
      - ./backstage:/app

  backstage-frontend:
    build:
      context: backstage
      dockerfile: Dockerfile
    command:
      - yarn
      - serve
    ports:
      - 3000:3000
    volumes:
      - ./backstage:/app

  backstage-database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
