services:
  backstage:
    build:
      context: backstage
      dockerfile: packages/backend/Dockerfile
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      GITHUB_TOKEN: abc
    ports:
      - 7007:7007

  backstage-db:
    image: postgres:15-alpine
    restart: always
    environment:
      # NOT RECOMMENDED for a production environment. Trusts all incoming connections.
      POSTGRES_HOST_AUTH_METHOD: trust
