services:
  backstage-backend:
    build:
      context: backstage
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
    ports:
      - 7007:7007
    volumes:
      - ./backstage:/app

  backstage-frontend:
    build:
      context: backstage
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backstage:/app

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

#  backend:
#  frontend:
