services:
#  backstage-backend:
#    build:
#      context: backstage/packages/backend
#      dockerfile: Dockerfile
#    command:
#      - yarn
#      - start-backend
#    environment:
#      POSTGRES_HOST: database
#      POSTGRES_USER: postgres
#    volumes:
#      - ./backstage:/app
#
#  backstage-frontend:
#    build:
#      context: backstage/packages/backend
#      dockerfile: Dockerfile
#    command:
#      - yarn
#      - start
#    environment:
#      POSTGRES_HOST: database
#      POSTGRES_USER: postgres
#    volumes:
      - ./backstage:/app

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

#  backend:
#  frontend:
