<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8WTIBfo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8WTIBfo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8WTIBfo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8WTIBfo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8WTIBfo\App_KernelDevDebugContainer([
    'container.build_hash' => '8WTIBfo',
    'container.build_id' => '51a97256',
    'container.build_time' => 1674326999,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8WTIBfo');
